# Define the environment.
language: php
sudo: required
services:
  - mysql
  - docker
php:
  - 5.6
  - 7
env:
  - COMPOSER_EXIT_ON_PATCH_FAILURE=1
  - IP=$(hostname -I | cut -d' ' -f1)
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.bower

# Install dependencies.
install:
  - nvm install
  - yarn install
  - node_modules/.bin/gulp install
  - vendor/bin/drupal init -n

# Perform whatever steps are needed to setup the site for testing.
# This could mean a fresh install, or a download/import of a sanitized copy of a production-like database.
before_script:
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost'"
  - cp ci/settings.travis.php web/sites/default/settings.local.php
  - vendor/bin/drupal --root=web/ -n chain --uri=http://default --file=../ci/prepare-site.yml
  - node_modules/.bin/gulp build

# Perform all testing steps, including static code analysis, unit, and web tests.
script:
  - nohup vendor/bin/drupal --root=web/ --uri=http://default -v -n server 0.0.0.0:8888 > /dev/null 2>&1 &
  - vendor/bin/drupal --root=web/ --uri=http://default -n cache:rebuild all
  - node_modules/.bin/gulp check
  - node_modules/.bin/gulp test --base-url="http://${IP}:8888"

